version: "3.9"

services:
  terraform:
    image: hashicorp/terraform:1.1.9
    platform: linux/x86_64
    working_dir: /usr/local/aws-resource-manager
    volumes:
      - .:/usr/local/aws-resource-manager
    env_file:
      - ./.env
    tty: true
